version: "2"
services:
  monitor-docker-slack:
    container_name: monitor-docker-slack
    image: petekaik/monitor-docker-slack:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SLACK_CHANNEL: "$SLACK_CHANNEL"
      SLACK_USERNAME: "$SLACK_USERNAME"
      SLACK_TOKEN: "$SLACK_TOKEN"
      MSG_PREFIX: "$MSG_PREFIX"
    restart: always
